template = "https://github.com/giellalt/template-lang-und"
rev_id = 274
template_sha = "43a0f0c0afaa856365e2bf3d3cb7eae06d27cc4d"

[replacements]
__GLOTTOLOG_ID__ = "hung1274"
__REPO__ = "lang-hun"
__UND2C__ = "hu"
__UNDEFINED__ = "Hungarian"
__UND__ = "hun"
