template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "hung1274"
__REPO__ = "lang-hun"
__UND2C__ = "hu"
__UNDEFINED__ = "Hungarian"
__UND__ = "hun"
